import type { Metadata } from "next"
import { Nunito } from "next/font/google"
import Provider from "./AppProvider"
import "./globals.css"

const font = Nunito({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "TimeSheet Management",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
